# Workflow to ensure whenever a Github PR is submitted, 
# a JIRA ticket gets created automatically. 
name: Manual Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the master branch
  push:
    branches:
      - master
      - main
jobs:
  install-dependencies-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install -r starter/requirements.txt
      - id: some-pytest
        run: pytest --exitfirst ./starter
        shell: bash
      - id: flake8-test
        run: flake8 ./starter
        shell: bash
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install -r starter/requirements.txt
      - id: change-render-env-variable
        run: |
          echo "TIME=$(date)" > env.txt
          export RENDER_TOKEN=${{ secrets.RENDER_API_KEY }}
          render-cli set-env -sn nd0821-c3-starter-code -f env.txt
        shell: bash
